[package]
name = "pngu"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.4", features = ["json", "blocking"]}
hex = "0.4.3"
rand = "0.8.4"
structopt = "0.3"
image = "0.23.14"
png = "0.17.2"
